"""Shared controlled vocabulary for landscape-painting retrieval and graphing."""

from __future__ import annotations

LANDSCAPE_DOMAIN_LEXICON: dict[str, str] = {
    "先秦": "DYNASTY",
    "秦汉": "DYNASTY",
    "魏晋南北朝": "DYNASTY",
    "隋": "DYNASTY",
    "隋代": "DYNASTY",
    "隋朝": "DYNASTY",
    "唐": "DYNASTY",
    "唐代": "DYNASTY",
    "唐朝": "DYNASTY",
    "大唐": "DYNASTY",
    "五代十国": "DYNASTY",
    "五代": "DYNASTY",
    "宋": "DYNASTY",
    "宋代": "DYNASTY",
    "宋朝": "DYNASTY",
    "大宋": "DYNASTY",
    "北宋": "DYNASTY",
    "南宋": "DYNASTY",
    "辽金西夏": "DYNASTY",
    "元": "DYNASTY",
    "元代": "DYNASTY",
    "元朝": "DYNASTY",
    "大元": "DYNASTY",
    "明": "DYNASTY",
    "明代": "DYNASTY",
    "明朝": "DYNASTY",
    "大明": "DYNASTY",
    "清": "DYNASTY",
    "清代": "DYNASTY",
    "清朝": "DYNASTY",
    "大清": "DYNASTY",
    "近现代": "DYNASTY",
    "王维": "PERSON",
    "荆浩": "PERSON",
    "关仝": "PERSON",
    "范宽": "PERSON",
    "李成": "PERSON",
    "米芾": "PERSON",
    "米友仁": "PERSON",
    "宗炳": "PERSON",
    "谢赫": "PERSON",
    "赵孟頫": "PERSON",
    "赵孟俯": "PERSON",
    "董源": "PERSON",
    "巨然": "PERSON",
    "郭熙": "PERSON",
    "马远": "PERSON",
    "夏圭": "PERSON",
    "倪瓒": "PERSON",
    "倪云林": "PERSON",
    "云林子": "PERSON",
    "黄公望": "PERSON",
    "黄大痴": "PERSON",
    "一峰道人": "PERSON",
    "王蒙": "PERSON",
    "吴镇": "PERSON",
    "石涛": "PERSON",
    "原济": "PERSON",
    "大涤子": "PERSON",
    "苦瓜和尚": "PERSON",
    "弘仁": "PERSON",
    "渐江": "PERSON",
    "髡残": "PERSON",
    "石溪": "PERSON",
    "八大山人": "PERSON",
    "朱耷": "PERSON",
    "王时敏": "PERSON",
    "王鉴": "PERSON",
    "王翚": "PERSON",
    "王原祁": "PERSON",
    "董其昌": "PERSON",
    "沈周": "PERSON",
    "文徵明": "PERSON",
    "文征明": "PERSON",
    "唐寅": "PERSON",
    "仇英": "PERSON",
    "展子虔": "PERSON",
    "王希孟": "PERSON",
    "四王": "SCHOOL",
    "四僧": "SCHOOL",
    "元四家": "SCHOOL",
    "南宋四家": "SCHOOL",
    "北宗": "SCHOOL",
    "南宗": "SCHOOL",
    "南北宗": "SCHOOL",
    "华亭派": "SCHOOL",
    "吴门画派": "SCHOOL",
    "浙派": "SCHOOL",
    "披麻皴": "TECHNIQUE",
    "斧劈皴": "TECHNIQUE",
    "雨点皴": "TECHNIQUE",
    "卷云皴": "TECHNIQUE",
    "解索皴": "TECHNIQUE",
    "折带皴": "TECHNIQUE",
    "牛毛皴": "TECHNIQUE",
    "荷叶皴": "TECHNIQUE",
    "泼墨": "TECHNIQUE",
    "没骨": "TECHNIQUE",
    "浅绛": "TECHNIQUE",
    "金碧": "TECHNIQUE",
    "青绿": "TECHNIQUE",
    "青绿山水": "TECHNIQUE",
    "水墨": "TECHNIQUE",
    "笔墨": "TECHNIQUE",
    "矿物色": "TECHNIQUE",
    "留白": "CONCEPT",
    "一河两岸": "CONCEPT",
    "经营位置": "CONCEPT",
    "置阵布势": "CONCEPT",
    "三远法": "CONCEPT",
    "高远": "CONCEPT",
    "深远": "CONCEPT",
    "平远": "CONCEPT",
    "虚实相生": "CONCEPT",
    "计白当黑": "CONCEPT",
    "疏密相间": "CONCEPT",
    "纵横开合": "CONCEPT",
    "边角构图": "CONCEPT",
    "点景": "CONCEPT",
    "点景建筑": "CONCEPT",
    "桥梁意象": "CONCEPT",
    "桥隐": "CONCEPT",
    "禅境": "CONCEPT",
    "黑白虚实": "CONCEPT",
    "仿古": "CONCEPT",
    "米氏云山": "CONCEPT",
    "富春山居图": "WORK_OF_ART",
    "溪山行旅图": "WORK_OF_ART",
    "林泉高致": "WORK_OF_ART",
    "林泉高致集": "WORK_OF_ART",
    "画山水序": "WORK_OF_ART",
    "筆法記": "WORK_OF_ART",
    "笔法记": "WORK_OF_ART",
}

LANDSCAPE_ALIAS_DICT: dict[str, str] = {
    "隋代": "隋",
    "隋朝": "隋",
    "唐代": "唐",
    "唐朝": "唐",
    "大唐": "唐",
    "五代": "五代十国",
    "宋代": "宋",
    "宋朝": "宋",
    "大宋": "宋",
    "元代": "元",
    "元朝": "元",
    "大元": "元",
    "明代": "明",
    "明朝": "明",
    "大明": "明",
    "清代": "清",
    "清朝": "清",
    "大清": "清",
    "倪云林": "倪瓒",
    "云林子": "倪瓒",
    "黄大痴": "黄公望",
    "一峰道人": "黄公望",
    "赵孟俯": "赵孟頫",
    "文征明": "文徵明",
    "石涛": "原济",
    "大涤子": "原济",
    "苦瓜和尚": "原济",
    "弘仁": "渐江",
    "髡残": "石溪",
    "八大山人": "朱耷",
}

QUERY_STOP_TERMS: set[str] = {
    "根据",
    "文献",
    "资料",
    "主要",
    "说明",
    "什么",
    "问题",
    "如何",
    "是否",
    "比较",
    "差异",
    "中的",
    "中国",
    "山水画",
    "研究",
    "请基于",
    "整理",
    "等同",
    "属于",
    "使用",
    "参与",
    "生成",
    "直接",
    "现代",
    "主要",
    "决定",
    "组成",
}

MODERN_NOISE_TERMS: set[str] = {
    "AI",
    "BIM",
    "ComfyUI",
    "LoRA",
    "Midjourney",
    "NFT",
    "OLED",
    "Photoshop",
    "RGB",
    "Stable Diffusion",
    "Transformer",
    "区块链",
    "云计算",
    "无人机",
    "手机",
    "数位板",
    "数码相机",
    "现代相机",
    "相机镜头",
    "摄影术",
    "短视频",
    "空调",
    "制冷技术",
    "摩天楼",
    "商业店铺",
    "店铺选址",
    "木工",
    "斧头劈柴",
    "施工安全",
    "白色油漆",
    "油漆",
    "打印机",
    "分辨率",
    "虚拟现实",
    "头显",
    "高速公路",
    "立交桥",
    "电脑",
    "水冷",
    "黑白墨盒",
    "图像压缩",
    "图像生成",
    "生成模型",
    "生成图",
    "采样器",
    "网页素材",
    "复制粘贴",
    "房地产",
    "小区景观",
    "西方抽象表现主义",
    "抽象表现主义",
    "显示器",
    "版权",
}


def normalize_domain_entity(entity_name: str) -> str:
    return LANDSCAPE_ALIAS_DICT.get(entity_name, entity_name)
